---
name: CI
on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches:
      - main

jobs:
  detect_changes:
    name: detect changes
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      bun: ${{ steps.filter.outputs.bun }}
      shell: ${{ steps.filter.outputs.shell }}
      ghaction: ${{ steps.filter.outputs.ghaction }}
      yaml: ${{ steps.filter.outputs.yaml }}
      ts_js: ${{ steps.filter.outputs.ts_js }}
      biome_supported: ${{ steps.filter.outputs.biome_supported }}
      markdown: ${{ steps.filter.outputs.markdown }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          # work with push on main branch
          base: ${{ github.ref }}
          # biome_supported according to https://biomejs.dev/internals/language-support/
          filters: |
            bun:
              - 'apps/bun-nestjs-pg/**'
            shell:
              - '**/*.sh'
            ghaction:
              - '.github/workflows/*.{yaml,yml}'
            yaml: &yaml
              - '**/*.{yaml,yml}'
            ts_js: &ts_js
              - '**/*.{js,jsx,ts,tsx}'
              - '**/package.json'
              - '**/package-lock.json'
              - '**/yarn.lock'
              - '**/pnpm-lock.yaml'
            biome_supported:
              - *ts_js
              - '**/*.json'
              - '**/*.{html,astro,vue,svelte}'
              - '**/*.css'
              - *yaml
              - '**/*.graphql'
              - 'apps/bun-nestjs-pg/**'
            markdown:
              - '**/*.{md,mdx,markdown}'
  shellcheck:
    name: shellcheck
    needs: detect_changes
    if: ${{ needs.detect_changes.outputs.shell == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          reporter: github-pr-review
  shfmt:
    name: shfmt
    needs: detect_changes
    if: ${{ needs.detect_changes.outputs.shell == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-shfmt@v1
  actionlint:
    name: actionlint
    needs: detect_changes
    if: ${{ needs.detect_changes.outputs.ghaction == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-pr-review
          level: warning
  yamllint:
    name: yamllint
    needs: detect_changes
    if: ${{ needs.detect_changes.outputs.yaml == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yamllint
        uses: reviewdog/action-yamllint@v1
        with:
          reporter: github-pr-review
          level: warning
  misspell:
    name: misspell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-misspell@v1
        with:
          reporter: github-pr-review
          level: warning
          locale: "US"
  biome:
    name: biome
    needs: detect_changes
    if: ${{ needs.detect_changes.outputs.biome_supported == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: mongolyy/reviewdog-action-biome@v1
        with:
          reporter: github-pr-review
          fail_on_error: true
  alex:
    name: alex
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-alex@v1
        with:
          reporter: github-pr-review
          level: warning
  tsc:
    name: tsc
    needs: biome
    if: ${{ needs.detect_changes.outputs.ts_js == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EPMatt/reviewdog-action-tsc@v1
        name: tsc apps/nestjs
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          fail_on_error: true
          workdir: apps/nestjs
  unit_tests:
    name: unit-tests
    needs: tsc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - run: npm install
      - run: npm run test:ci
      - name: Upload apps/nestjs coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: apps/nestjs/coverage/coverage-final.json
          flags: apps/nestjs
  bun:
    name: bun build
    needs: biome
    if: ${{ needs.detect_changes.outputs.bun == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/bun-nestjs-pg
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun build ./src/main.ts
  markdown-link-check:
    name: markdown link check
    needs: detect_changes
    if: ${{ needs.detect_changes.outputs.markdown == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          base-branch: main
  e2e-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/nextjs-example
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: daun/playwright-report-summary@v3
        if: always()
        with:
          report-file: ./apps/nextjs-example/test-results/results.json
